.PHONY: all withAt seperator witoutAt

all: withAt seperator withoutAt

withAt:
	@echo hi
# output:
# hi

seperator:
	@echo --------------------------------
# 这个 target 起到分割的目的

withoutAt:
	echo hi
# output:
# echo hi
# hi
# make 会先打印命令 `echo hi`, 再打印结果 `hi`. 我们只想打印结果, 因此要加 @ 符号
